language: node_js

node_js:
  - 'stable'

services:
  - 'xvfb'

before_script:
  - npm install -g grunt-cli bower
  - bower install
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"

script:
  - grunt karma:ci
